### ISSUE TITLE
Issue running studio with spaces in path to schema

### ISSUE THREAD

**Issue by dennis27** [redwoodjs/studio#37]
The full path to my code directory has spaces.  When I run yarn rw studio below is a snippet of the output.

` shortMessage: 'Command failed with exit code 1: npx prisma migrate deploy --schema /Users/myname/path and space/Code/my_secret_proj/node_modules/@redwoodjs/studio/api/db/schema.prisma',
  command: 'npx prisma migrate deploy --schema /Users/myname/path and space/Code/my_secret_proj/node_modules/@redwoodjs/studio/api/db/schema.prisma',
  escapedCommand: 'npx prisma migrate deploy --schema "/Users/myname/path" and "space/Code/my_secret_proj/node_modules/@redwoodjs/studio/api/db/schema.prisma"',
  exitCode: 1,
  signal: undefined,
  signalDescription: undefined,
  stdout: undefined,
  stderr: undefined,
  failed: true,
  timedOut: false,
  isCanceled: false,
  killed: false
`

**Comment by dthyresson** [comment]
Hi @dennis27 and thanks for trying Studio and for reporting this issue. Back in the early days of Redwood we had similar issues with spaces in paths and I recall having to fix a few. The solution is hopefully similar and we can get a fix in soon.

**Comment by dthyresson** [comment]
Will look into if these paths need to be enclosed in quotes or other ways to allow spaces: https://github.com/redwoodjs/studio/blob/80bb931a1355b559d09199a43d8a38e7af72ab8f/api/src/server.ts#L54
